<a href="https://colab.research.google.com/github/Simon006/Fluent_Python_notes/blob/main/chapter02_%E5%BA%8F%E5%88%97%E6%9E%84%E6%88%90%E7%9A%84%E6%95%B0%E7%BB%84%EF%BC%88%E7%BB%AD%EF%BC%89.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

python中像元组、列表和字符串这些序列类型都支持切片操作，这里给出示例说明切片和区间忽略最后一个元素的好处。

In [1]:
my_list = [1,2,3,4,5,6,7]
print(range(3))     #两种表达皆返回3个元素
print(my_list[:3])

print(my_list[3:])

range(0, 3)
[1, 2, 3]
[4, 5, 6, 7]


python还有对对象切片的功能

In [2]:
s = 'bicycle'
print(s[::-1])
print(s[::3])
print(s[::-2])

elcycib
bye
eccb


切片放在赋值语句的左边，或者作为del对象的对象，就可以是西安对序列进行**嫁接，切除**或者**修改**操作。

In [4]:
list1=list(range(10))
print(list1)
list1[2:5] = [30,20]
print(list1)
 #可以发现切片操作中完全替换了三元素切片和二元素列表

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 30, 20, 5, 6, 7, 8, 9]


需要注明的是，这种切片替代操作需要**右边是可迭代对象**，单独的对象需要转化为可迭代的序列。

In [5]:
#list1[2:5]=1  会报错
list1[2:5]=[1]
print(list1)

[0, 1, 1, 6, 7, 8, 9]


序列对+和*操作的支持，他们遵循不修改原有操作对象，构建一个全新序列的规律。见下例子：

In [7]:
a='apple'
b=5*a
print("id_a:",id(a))
print("id_5*a:",id(b))

id_a: 140349968910320
id_5*a: 140349968706416


这里面有一个细节，加入想在序列a中存在对其他可变对象的引用的话，那么a*n将生成n个对a的引用，这导致没有达到预期的效果。

In [8]:
my_list1 = [['_']*3for i in range(3)]
my_list1[0][1]='x'
my_list2 = [['_']*3]*3
my_list2[0][1] = 'x'
print(my_list1)
print(my_list2) 

[['_', 'x', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', 'x', '_'], ['_', 'x', '_'], ['_', 'x', '_']]


我们来看list1和list2的等价代码

In [14]:
a=[]
for i in range(3):
  row = ['_']*3
  a.append(row)
print(a)
a[0][1]='x'
print(a)   

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', 'x', '_'], ['_', '_', '_'], ['_', '_', '_']]


In [15]:
row = ['_']*3
a = []
for i in range(3):
  a.append(row)
print(a)
a[0][1]='x'
print(a)  

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', 'x', '_'], ['_', 'x', '_'], ['_', 'x', '_']]


同理+和\*有着相似相近的性质，可以相互类比类推，甚至+=和\*=也有着类似的性质，书中用巩固都的例子展示了对不可变序列进行**重复拼接操作的时候效率会很低**，因为每次都产生了一个新的对象，需要解释器将原来对象中的元素先复制到新的对象中，再追加新的元素。

In [18]:
l=[1,2,3]
print("id_l",id(l))
l*=3
print("id_l*3:",id(l))

t=(1,2,3)
print("id_t",id(t))
t*=3
print("id_t*3",id(t))


id_l 140349968067392
id_l*3: 140349968067392
id_t 140349968989712
id_t*3 140349968878672


我们可以从这些例子中学到元组的不可变性的表现，但书中的例子更有提到，在元组中存储可变序列是相当不妙的事。
书中提到虽然列表既灵活又简单，但面对各类需求时，我们可能会有更好的选择。比如，要存放 1000 万个浮点数的话，**数组（array）**的效率要高得多，因为数组在背后存的并不是 float 对象，而是数字的机器翻译，也就是字节表述。这一点就跟 C 语言中的数组一样。再比如说，如果需要频繁对序列做先进先出的操作，deque（双端队列）的速度应该会更快。

In [24]:
from collections import deque

dq=deque(range(10),maxlen=10)
print(dq)

dq.rotate(3)
print(dq)
#队列的旋转参数n，大于零的时候队里最右边n个元素会被移动到队列的左边，同理类似有n小于零时情形
dq.rotate(-4)
print(dq)

#添加元素操作,从右、从左。
dq.extend([1,2,3])
print(dq)
dq.extendleft([3,2,1])
print(dq)


deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)
deque([4, 5, 6, 7, 8, 9, 0, 1, 2, 3], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)


当我们要引用字节数据的某个片段（注意是对象内的某一个片段）的时候，可用内存视图直接引用目标内存，**没有额外的复制行为**，因此，可读取最新的数据，在目标对象允许的情况下，还可以执行写操作。若是还想要把目标复制出来，可以用tobytes、tolist 方法，复制后的**数据与原对象无关**，同样不会影响视图本身。
内存视图是泛化和去数学化的 NumPy 数组。它让你在不需要复制内容的前提下，在数据结构之间共享内存。其中数据结构可以是任何形式，比如 PIL 图片、SQLite 数据库和 NumPy 的数组，等等。这个功能在处理大型数据集合的时候非常重要

In [26]:
#memoryview.cast 的概念跟数组模块类似，能用不同的方式读写同一块内存数据，而且内容字节不会随意移动。
import array
import numpy as np
from sklearn.neighbors import KDTree
from time import time


arr = array.array('h', [1, 2, 3])
memv_arr = memoryview(arr)
# 把 signed short 的内存使用 char 来呈现
memv_char = memv_arr.cast('B') 
print('Short', memv_arr.tolist())
print('Char', memv_char.tolist())
memv_char[1] = 2  # 更改 array 第一个数的高位字节
# 0x1000000001
print(memv_arr.tolist(), arr)
print('-' * 10)
bytestr = b'123'
# bytes 是不允许更改的
try:
    bytestr[1] = '3'
except TypeError as e:
    print(repr(e))
memv_byte = memoryview(bytestr)
print('Memv_byte', memv_byte.tolist())
# 同样这块内存也是只读的
try:
    memv_byte[1] = 1
except TypeError as e:
    print(repr(e))


pts = np.random.randn(10, 3)
print("pts:", pts)
# t1 = time()
tree = KDTree(pts)
# print("kdtree build time:", time() - t1)
pts_rebuild_copy = np.array(tree.data)
pts_rebuild_nocopy = np.array(tree.data, copy=False)
pts_rebuild_copy[0] = [1, 1, 1]
print("pts_1:", pts)
pts_rebuild_nocopy[1] = [1, 1, 1]
print("pts_2:", pts)


Short [1, 2, 3]
Char [1, 0, 2, 0, 3, 0]
[513, 2, 3] array('h', [513, 2, 3])
----------
TypeError("'bytes' object does not support item assignment")
Memv_byte [49, 50, 51]
TypeError('cannot modify read-only memory')
pts: [[ 0.82874274 -1.75716543  0.96411637]
 [ 0.94011531 -0.97113615  0.20303474]
 [ 0.60825124  0.41945095 -0.09165098]
 [-0.45646365  0.1456098  -0.67319475]
 [-1.32831719 -2.14648601  1.7806107 ]
 [ 1.09733725  0.4233083   1.30916484]
 [ 0.08862721 -0.16801569 -0.674484  ]
 [ 0.02444206 -0.04779311  0.44813211]
 [-0.48934372 -1.1426362  -0.29665071]
 [ 1.44814859 -0.04869548  0.91531527]]
pts_1: [[ 0.82874274 -1.75716543  0.96411637]
 [ 0.94011531 -0.97113615  0.20303474]
 [ 0.60825124  0.41945095 -0.09165098]
 [-0.45646365  0.1456098  -0.67319475]
 [-1.32831719 -2.14648601  1.7806107 ]
 [ 1.09733725  0.4233083   1.30916484]
 [ 0.08862721 -0.16801569 -0.674484  ]
 [ 0.02444206 -0.04779311  0.44813211]
 [-0.48934372 -1.1426362  -0.29665071]
 [ 1.44814859 -0.04869548  0.91

可见，tree.data就是指向内存中存放pts的地址，np.array(tree.data, copy=True)是对pts的deepcopy而np.array(tree.data, copy=False)是对pts的浅拷贝，memoryview.cast方法就相当于不改变内存位置下的**深拷贝**。可以精确修改一个数组的字节，并将**内存打包返回**。